--- #YAML:1.0
name:               IO-Socket-Socks
version:            0.62_3
abstract:           Provides a way to create socks client or server both 4 and 5 version.
author:
    - Oleg G <oleg@cpan.org>
license:            lgpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.52
build_requires:
    Test::More:  0.88
requires:
    constant:          1.03
    IO::Select:        0
    IO::Socket::INET:  0
resources:
    repository:  https://github.com/olegwtf/p5-IO-Socket-Socks
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
